import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  traktHistoryEntries: defineTable({
    historyId: v.string(),
    watchedAt: v.string(),
    watchedAtMs: v.number(),
    entryType: v.union(v.literal("movie"), v.literal("show"), v.literal("episode")),
    title: v.string(),
    subtitle: v.optional(v.string()),
    posterUrl: v.string(),
    href: v.string(),
    showTitle: v.optional(v.string()),
    episodeTitle: v.optional(v.string()),
    season: v.optional(v.number()),
    episode: v.optional(v.number()),
    runtimeMinutes: v.number(),
    aggregateKey: v.string(),
    aggregateType: v.union(v.literal("movie"), v.literal("show")),
    aggregateTitle: v.string(),
    aggregateHref: v.string(),
    aggregatePosterUrl: v.string(),
    aggregateRuntimeMinutes: v.number(),
  })
    .index("by_historyId", ["historyId"])
    .index("by_watchedAtMs", ["watchedAtMs"]),
  traktDailyActivity: defineTable({
    date: v.string(),
    totalSeconds: v.number(),
    movieSeconds: v.number(),
    episodeSeconds: v.number(),
    updatedAtMs: v.number(),
  }).index("by_date", ["date"]),
  traktState: defineTable({
    key: v.string(),
    syncedAtMs: v.number(),
    currentWatching: v.optional(
      v.object({
        type: v.union(v.literal("movie"), v.literal("show"), v.literal("episode")),
        title: v.string(),
        showTitle: v.optional(v.string()),
        episodeTitle: v.optional(v.string()),
        season: v.optional(v.number()),
        episode: v.optional(v.number()),
        posterUrl: v.string(),
        url: v.string(),
        progress: v.optional(v.number()),
        startedAt: v.optional(v.string()),
        expiresAt: v.optional(v.string()),
      }),
    ),
  }).index("by_key", ["key"]),
  traktAuthState: defineTable({
    key: v.string(),
    accessToken: v.string(),
    refreshToken: v.string(),
    tokenType: v.optional(v.string()),
    scope: v.optional(v.string()),
    createdAtSeconds: v.optional(v.number()),
    expiresInSeconds: v.optional(v.number()),
    expiresAtMs: v.number(),
    updatedAtMs: v.number(),
  }).index("by_key", ["key"]),
  healthDailySummaries: defineTable({
    date: v.string(),
    steps: v.number(),
    distanceMeters: v.number(),
    activeCaloriesKcal: v.number(),
    totalCaloriesKcal: v.number(),
    exerciseSeconds: v.number(),
    sleepSeconds: v.number(),
    sleepAsleepSeconds: v.optional(v.number()),
    sleepInBedSeconds: v.optional(v.number()),
    exerciseSessions: v.number(),
    sleepSessions: v.number(),
    heartRateMinBpm: v.optional(v.number()),
    heartRateAvgBpm: v.optional(v.number()),
    heartRateMedianBpm: v.optional(v.number()),
    heartRateMaxBpm: v.optional(v.number()),
    heartRateLatestBpm: v.optional(v.number()),
    heartRateLatestAtMs: v.optional(v.number()),
    sources: v.array(v.string()),
    updatedAtMs: v.number(),
  }).index("by_date", ["date"]),
  healthActivityEvents: defineTable({
    externalId: v.string(),
    date: v.string(),
    kind: v.union(v.literal("exercise"), v.literal("sleep")),
    title: v.string(),
    activityType: v.optional(v.string()),
    startTime: v.string(),
    endTime: v.string(),
    startTimeMs: v.number(),
    endTimeMs: v.number(),
    durationSeconds: v.number(),
    distanceMeters: v.optional(v.number()),
    steps: v.optional(v.number()),
    caloriesKcal: v.optional(v.number()),
    heartRateMinBpm: v.optional(v.number()),
    heartRateAvgBpm: v.optional(v.number()),
    heartRateMaxBpm: v.optional(v.number()),
    sourcePackageName: v.optional(v.string()),
    metadataId: v.optional(v.string()),
    updatedAtMs: v.number(),
  })
    .index("by_externalId", ["externalId"])
    .index("by_startTimeMs", ["startTimeMs"])
    .index("by_date", ["date"]),
  healthSyncState: defineTable({
    key: v.string(),
    syncSource: v.string(),
    lastWindowStartMs: v.number(),
    lastWindowEndMs: v.number(),
    lastSyncedAtMs: v.number(),
    dailySummaries: v.number(),
    activityEvents: v.number(),
    currentStats: v.optional(
      v.object({
        date: v.string(),
        steps: v.optional(v.number()),
        heartRateBpm: v.optional(v.number()),
        heartRateAtMs: v.optional(v.number()),
        sources: v.array(v.string()),
        updatedAtMs: v.number(),
      }),
    ),
  }).index("by_key", ["key"]),
});
